FROM  alpine:3.21

WORKDIR /flask-app

COPY app requirments.txt /flask-app/ 

RUN apk update && apk add --no-cache  python3 py3-pip && pip install --break-system-packages -r requirments.txt

EXPOSE 5000

RUN addgroup -S app-group && adduser -S app-user -G app-group

USER app-user

ENTRYPOINT [ "python3" , "flask-app.py" ]
